IF OBJECT_ID('operational_budgets', 'U') IS NULL
BEGIN
    CREATE TABLE operational_budgets (
        id INT IDENTITY(1,1) PRIMARY KEY,
        client_key VARCHAR(100) NOT NULL UNIQUE,
        budget_code VARCHAR(150) NOT NULL,
        cost_code VARCHAR(100),
        acct_budget VARCHAR(100),
        large_account VARCHAR(100),
        cost_code_1 VARCHAR(100),
        dept_sect VARCHAR(150),
        acc_no VARCHAR(100),
        acc_desc VARCHAR(255),
        item_name VARCHAR(255) NOT NULL,
        reason VARCHAR(255),
        initial_budget_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        initial_budget_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        jan_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        jan_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        feb_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        feb_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        mar_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        mar_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        apr_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        apr_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        may_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        may_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        jun_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        jun_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        jul_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        jul_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        aug_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        aug_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        sep_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        sep_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        oct_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        oct_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        nov_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        nov_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        dec_plan DECIMAL(18, 2) NOT NULL DEFAULT 0,
        dec_actual DECIMAL(18, 2) NOT NULL DEFAULT 0,
        created_at DATETIMEOFFSET DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIMEOFFSET DEFAULT CURRENT_TIMESTAMP
    );
END
GO
